### ISSUE TITLE
Projects Invoice: Error after removing the advanced payment 

### ISSUE THREAD

**Issue by ishayyaari** [MiYa-Solutions/sbcx#717]
"Failed to create the invoice.
Invoice items: Invice is empty and therefore invalid"

I removed the payment options from  - /views/invoices/_invoice_list.html.erb 
and can't issue an invoice from the Project Show page

**Comment by markmilman** [comment]
You get this error when there is nothing to invoice for.  Is one of the
jobs complete?

**Comment by ishayyaari** [comment]
Right - sorry you can close this

**Comment by markmilman** [comment]
On a second thought, if the error message wasn't clear to you,  then it will probably not be clear to other users.  Leaving this open to enhance the message
